### ISSUE TITLE
Screenshot shuts down after 3min

### ISSUE THREAD

**Issue by Shadowval** [mortenjust/androidtool-mac#110]
As soon as I start recording, after 3 minutes it stops and create the file. Because of this, I can not record more than 3 minutes. Ideas ?

**Comment by manastungare** [comment]
3 minutes is the maximum time limit supported by `adb screenrecord`, the underlying tool used by AndroidTool.
https://developer.android.com/studio/command-line/adb.html#screenrecord

**Comment by mortenjust** [comment]
+1, working as expected for now

**Comment by Shadowval** [comment]
yes but it's worked before... I did video more 3 minutes with this soft...

**Comment by mortenjust** [comment]
Can you get more than 3 minutes using [raw ADB commands](https://developer.android.com/studio/command-line/adb.html#screenrecord)?

**Comment by erichkleung** [comment]
@mortenjust I think the only way to get around the 3 minute limit is to re-record, and combine the videos together.
