### ISSUE TITLE
[MotoX] Video Recording not working on first-gen Moto X

### ISSUE THREAD

**Issue by dmay-work** [mortenjust/androidtool-mac#12]
As you can see from the attached screenshot, video signal seems to be mangled. Any ideas?

Moto X / Android 4.4.4

![motox-androidtool](https://cloud.githubusercontent.com/assets/1301209/7394128/617f43b4-ee57-11e4-92c7-ff00a4499095.png)

**Comment by mortenjust** [comment]
Is this 1st gen moto x?

**Comment by dmay-work** [comment]
Yes, Model XT1060

**Comment by mortenjust** [comment]
checked in a fix that reads the device's display dimensions. Will test a bit and then release

**Comment by dmay-work** [comment]
Sorry for the late reply. I build the project based on latest master branch today and tested again. It looks like it has improved, but is still not great. See attached screenshot. It's also not playing back video.

![screen shot 2015-05-07 at 2 00 39 pm](https://cloud.githubusercontent.com/assets/1301209/7523463/8edac03e-f4c1-11e4-853b-e9fcdaeee5ba.png)

**Comment by mortenjust** [comment]
Thanks for testing against master. Now that you have it running, could you try and go to Preferences and set the scale slider (the bottom one) to 1x by sliding it all the way to the right?

**Comment by mortenjust** [comment]
Just checked in a version that has more rounded steps for the scale slider, but I'm still the most interested in your results for 1x

**Comment by dmay-work** [comment]
I can confirm that setting it to 1x does the trick. The default setting (0.7?) does not. Thanks for the help!

**Comment by mortenjust** [comment]
Changed the default setting to 1x
