### ISSUE TITLE
Crash attempting BugReport on Emulator

### ISSUE THREAD

**Issue by devunwired** [mortenjust/androidtool-mac#13]
When selecting "Take BugReport" for an emulator device, the application will crash 100% of the time with the following crash log:
https://gist.github.com/devunwired/ebbef4dd17028e6240f3

Tested with Android 5.0.1 x86 emulator. OS X Yosemite 10.10.3.

**Comment by mortenjust** [comment]
Reproduced and fixed in the latest version. Bug reports and custom scripts work, but screencaps don't seem to be possible over adb with emulators, let me know if you know a way.

**Comment by devunwired** [comment]
Your standard method used in [takeScreenshotOfDeviceWithSerial.sh](https://github.com/mortenjust/androidtool-mac/blob/master/AndroidTool/takeScreenshotOfDeviceWithSerial.sh) will work on the emulator also.

However, due to a bug in a handful of emulator versions (mainly 4.3-5.0) some of them do not support it. The bug was finally fixed for the 5.1 system images, though it hasn't been back-ported to the others. There is no deterministic way (other than attempting anyway and reporting an error) to determine which versions will work and which will not.
