### ISSUE TITLE
Crash when new devices come online

### ISSUE THREAD

**Issue by devunwired** [mortenjust/androidtool-mac#14]
I see this crash often (maybe 40% of the time) when the application is running and a new device or emulator comes online. In most cases, the device is connected to USB while booting and the crash occurs when the device is booted up. I'm assuming it's a similar pattern when the emulator is launched.

I don't know if it was the same crash log, but I have seen a few crashes when disconnecting a device/emulator as well.

Crash log at the following link:
https://gist.github.com/devunwired/94c04353d929153bab48

OS X Yosemite 10.10.3
Test Target(s) Used:
- Android 5.0.1 x86 Emulator
- Nexus 9
- Moto X (2nd Gen)

**Comment by mortenjust** [comment]
Do you have a feeling if this occurs only when an emulator is running?

**Comment by devunwired** [comment]
No, it definitely happened with devices as well (the devices I listed). I
can't speak to the frequency difference in either case.

**Comment by mortenjust** [comment]
Reproduced and fixed in 1.16, https://github.com/mortenjust/androidtool-mac/releases
