### ISSUE TITLE
Support for OnePlus One, OxygenOS?

### ISSUE THREAD

**Issue by IFSTREAM** [mortenjust/androidtool-mac#15]
It don't get any information whether it is even working on not. Not sure what would be the cause of this. Any ideas?

**Comment by mortenjust** [comment]
hey @IFSTREAM does "adb devices" give you anything? Is USB Debugging enabled?

**Comment by IFSTREAM** [comment]
Yeah! USB debugging is enabled. I'm guessing that the android SDK needs to
be installed doesn't it? :P

**Comment by mortenjust** [comment]
No SDK is needed, ADB is embedded in the app bundle. If you or anyone else with a OnePlus device with OxygenOS is up for it try and install the SDK and run adb devices and let me know what you see.

**Comment by IFSTREAM** [comment]
Got it working! Latest version it works perfect! :+1:
