### ISSUE TITLE
Support for emulators

### ISSUE THREAD

**Issue by tiwiz** [mortenjust/androidtool-mac#19]
Hello,

if you try to use AndroidTool with an emulator as Genymotion, connected through ip:port, every time you try to do something with it (screenshot, video or *any* script), the app crashes.

Moreover, it's not recognised as Genymotion but as generic *Google Nexus* device, as per screenshot (first device on top)
![Screenshot](http://i.imgur.com/SWDo4tj.png)

**Comment by mortenjust** [comment]
Newest version adds limited support for emulators. Screencaps don't seem to work. Let me know if know a way to do this with adb.

**Comment by tiwiz** [comment]
Hello,

with Genymotion (and I guess also with any other device connected through IP - so this could be potentially used also for ADB over WiFi), you can use the ip as a serial. For instance, to use screencap, you can use the following:

```
adb -s 192.168.56.100:5555 shell screencap -p /sdcard/mscreen.png 
adb -s 192.168.56.100:5555 pull /sdcard/mscreen.png
adb -s 192.168.56.100:5555 shell rm /sdcard/mscreen.png
```

I'm not 100% sure, but I think you can get the IP and the port by asking for the serial (when you use ```adb devices``` Genymotion is shown by that, instead of the serial). I can also try with Google standard emulator, if you need
