### ISSUE TITLE
If I switch the device, the tool does not refresh

### ISSUE THREAD

**Issue by venkys811** [mortenjust/androidtool-mac#2]
Being a tester, I keep switching the device connected, I have to close the tool and launch the tool everytime I wsitch te device. Would be great if it either detects automatically / have a refresh button to refresh the device that I have connected.

P.S: Have to say this is awesome tool!

**Comment by mortenjust** [comment]
@venkys811 which OS and Android device are you using?

**Comment by mortenjust** [comment]
The newest version has a manual refresh menu item / cmd+R. I'm still interested in knowing which OSX version you're on

**Comment by venkys811** [comment]
Hey @mortenjust , The OS version is Yosemite 10.10.3 and the devices that I was trying to switch were LG G3, Samsung S3, XIAOMI Note and a Nexus 5. I have not tried the new version, but will let you know if the new version helps. :-)

**Comment by mortenjust** [comment]
how did it go?

**Comment by mortenjust** [comment]
I'm not able to reproduce this. Please re-open if you can

**Comment by venkys811** [comment]
Works like a charm @mortenjust . :)

**Comment by mortenjust** [comment]
awesome, thanks for checking
