### ISSUE TITLE
Take Bugreport does not work with without modifications

### ISSUE THREAD

**Issue by devunwired** [mortenjust/androidtool-mac#22]
The current `Take Bugreport` script bundled with the app is as follows:
```
#!/bin/bash
declare -a arr
thisdir=$1 # $1 is the bundle resources path directly from the calling script file
serial=$2 # 
adb=$thisdir/adb


# --------------------
#
# Add your script below. When sending adb commands to the user-selected device, use "$adb -s $serial"
# 
# --------------------

TakeBugReport(){
	ldap=$(whoami)
	now=$(date +"%m-%d-%Y-%H-%M-%S")
	devicename=$($adb -s $serial shell getprop ro.product.name)
	finalFilename=$devicename-$ldap-$now.png
	finalFilename="${finalFilename//[$'\t\r\n ']}"

	$adb -s $serial bugreport > $finalFilename".txt"
	}

mkdir -p ~/Desktop/bugreport
cd ~/Desktop/AndroidTool
TakeBugReport
open . #opens the Android Tool folder in Finder after executing. Could be annoying
```

Out of the box, this does not work for any device. One of the following two modifications has to be made, either:

1. Manually create `~/Desktop/AndroidTool` so the script has a destination to enter
2. Change `cd ~/Desktop/AndroidTool` to `cd ~/Desktop/bugreport` so the output is placed in the created directory.

I believe option 2 was probably the intended purpose, but it's not clear why the script assumes that `~/Desktop/AndroidTool/` exists on the machine (it is is not created, nor part of the setup instructions).

**Comment by mortenjust** [comment]
ah - thanks, good catch. "Bugreport" was an early code name for the app

**Comment by mortenjust** [comment]
Committed for next release
