### ISSUE TITLE
Linux version?

### ISSUE THREAD

**Issue by wollac11** [mortenjust/androidtool-mac#26]
Is there any chance you would consider adapting this so it will work on Linux as well? I see it uses shell scripts which obviously would not be a problem but I guess the issue is the current use of swift?

**Comment by mortenjust** [comment]
The wrapper is purely MacOS currently. But I'd be more than happy to see Linux and Windows forks

**Comment by AndroidDeveloperLB** [comment]
Was going to ask for a Windows version too, but I see you've answered it. 
Maybe change the title?

**Comment by joshuapinter** [comment]
@AndroidDeveloperLB Did you ever find a good Windows alternative for this?
