### ISSUE TITLE
boot my phone

### ISSUE THREAD

**Issue by bizzy4758** [mortenjust/androidtool-mac#29]
SD card isn't programmed

**Comment by bizzy4758** [comment]
contact me if you can help this is very important for me right now I can't download anything else on my phone

**Comment by mortenjust** [comment]
Please be more specific. What did you do before you got the error? What exactly is the error message? Which phone do you have? Etc.

**Comment by bizzy4758** [comment]
my sd card doesn't get downloads on it I'll have the master reset it but I don't want to do that so I just want to get it boot it so I can get better reception and there's a lot pps aappsered if that doesn't need to be there they are expired in and not running my phone needs a makeover thank you Bizzy4758 1I can be reached at 909235220

**Comment by mortenjust** [comment]
ok, this is a forum for an Apple Mac application that lets you take photos of your screen. I can't help you with cleaning up your phone, sorry.

**Comment by bizzy4758** [comment]
When I bought the phone I wasn't aware that it needed a SD card to store memory on it and then they told me to buy one and put it in but I didn't  never get tnything stored on it the the error message said that it needed to be need mounted I didn't  know how to  mount it now I can't store anything on it and they want me to do a master reset and I don't want to lose everything. Bizzy4758 thank you for being concern

**Comment by bizzy4758** [comment]
When I bought the phone I wasn't aware that it needed a SD card to store memory on it and then they told me to buy one and put it in but I didn't  never get tnything stored on it the the error message said that it needed to be need mounted I didn't  know how to  mount it now I can't store anything on it and they want me to do a master reset and I don't want to lose everything. Bizzy4758 thank you for being concern
