### ISSUE TITLE
homebrew support

### ISSUE THREAD

**Issue by schwiz** [mortenjust/androidtool-mac#30]
Hey thanks for this tool, looks super useful. It would be great if you added this to homebrew for mac so I can easily install and get updates for this project.
Thanks!

**Comment by mortenjust** [comment]
Great idea. Will do it once a bit more stabilized

**Comment by macklinu** [comment]
For reference, it doesn't look like Homebrew itself is the appropriate place for distributing `.app`s, according to their [documentation](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Acceptable-Formulae.md#stuff-that-builds-a-app). However, there is something called [Homebrew Cask](https://github.com/caskroom/homebrew-cask), which is an [external command](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/External-Commands.md) specifically for distributing `.app`s.

I'm enjoying this tool and would also like to +1 this feature request. Thanks!

**Comment by razasyedh** [comment]
A formula was created in #23. You can install it under the name "androidtool". So all that's missing is a notice in the readme.

**Comment by schwiz** [comment]
Nice that is slick, got it installed through cask which I hadn't heard of thanks!
