### ISSUE TITLE
Phone may not be found on 10.10.3

### ISSUE THREAD

**Issue by bootstraponline** [mortenjust/androidtool-mac#37]
I launched the app and the UI is blank. Sometimes it displays.

![ui_bug_androidtoolmac](https://cloud.githubusercontent.com/assets/1173057/7529465/178f010c-f507-11e4-917b-1ee74ed9fa08.png)

**Comment by mortenjust** [comment]
Which phone? Which version of AndroidTool? Is USB debugging enabled on your phone? Are you able to reliably reproduce the blank screen?

**Comment by bootstraponline** [comment]
Nexus 7 tablet,  AndroidTool `Version 1.15 (7)`, yes USB debugging is disabled. No it's not reliable, after exiting and relaunching a few times it eventually goes away.

**Comment by mortenjust** [comment]
Please try the newest version and reopen if that did not solve it, along with what `adb devices` shows in your terminal. Thanks!
