### ISSUE TITLE
Corrupt video on Nexus 7

### ISSUE THREAD

**Issue by bootstraponline** [mortenjust/androidtool-mac#38]
I see a video error after the video recording command is complete.

![video_error](https://cloud.githubusercontent.com/assets/1173057/7529489/8f94a616-f507-11e4-9621-c3c916b41b6e.png)

**Comment by mortenjust** [comment]
is this the release or did you check out a master branch?

**Comment by bootstraponline** [comment]
release

**Comment by mortenjust** [comment]
ok, should be fixed in the next version set for release in 2 days. If not, please reopen this issue. Thanks for your help reporting this!
