### ISSUE TITLE
Crash On Launch

### ISSUE THREAD

**Issue by mandrachek** [mortenjust/androidtool-mac#4]
I use LittleSnitch (https://www.obdev.at/products/littlesnitch/index.html) and denied the application's attempt to make contact with mortenjust.com port 80.

![voila_capture 2015-04-28_10-32-25_am](https://cloud.githubusercontent.com/assets/1045440/7371952/ef6cbe5c-ed91-11e4-8fc4-c5524cf5289e.png)

This results in an immediate crash.

**Comment by hzsweers** [comment]
Same thing happens for one of our QA guys when trying to use it on his Mavericks laptop (10.9.5). No connection checking / firewall though.

**Comment by mortenjust** [comment]
Should be fixed in https://github.com/mortenjust/androidtool-mac/releases/tag/1.14
