### ISSUE TITLE
Please test the iOS version (Yosemite only)

### ISSUE THREAD

**Issue by mortenjust** [mortenjust/androidtool-mac#40]
I just merged a rocky iOS integration into Master. If you have a moment, please grab master and test the follwing

* Device appears in device list when connected, and disappears when disconnected
* Screenshot produces a PNG
* Screen recording produces a MOV and an animated GIF

![image](https://cloud.githubusercontent.com/assets/1548468/7529751/26862d58-f4f2-11e4-92b8-2eb7ad736cfd.png)

**Comment by clarklab** [comment]
Is there a special step to getting an iOS device to show up? I've got mine connected over USB, and iTunes can see it, but AndroidTool can't. Ideas?
