### ISSUE TITLE
Huawei MT2L03: Video recording doesn't start

### ISSUE THREAD

**Issue by clarklab** [mortenjust/androidtool-mac#43]
Is there any kind of trick to getting video recording to work? Taking screenshots works just fine, but when I click record, nothing happens. Well, I get a quick spinner sometimes, then nothing happens. Check out the gif below:

![android-tool-video](https://cloud.githubusercontent.com/assets/160409/7634064/0d4bddd4-fa1e-11e4-94d6-81f3b4ebdbb8.gif)

Any ideas?

**Comment by mortenjust** [comment]
Hm, haven't seen any Huawei phones yet. 

Is the scale set to 1x in Preferences? 

Does [http://www.cnet.com/how-to/how-to-record-your-screen-on-android-4-4-kitkat/](adb screen recording) work in Terminal?

**Comment by clarklab** [comment]
Yes, set to 1x.

Trying that link now.

More info: just tried on a Moto X, and while recording works, Android Tool doesn't act like it (no red button during record, no indication), but a video pops up at the end.

I'm using the newest download on the release page. Should I try the previous version?

**Comment by clarklab** [comment]
ps: stupid question, but do I need ADB/Android Studio/Whatever running on my Mac for this to work?

**Comment by mortenjust** [comment]
For the terminal commands you need the adb command line tool. You get it with the SDK or just [grab it from the repo](https://github.com/mortenjust/androidtool-mac/raw/master/AndroidTool/adb)

**Comment by clarklab** [comment]
oh, I meant do I need ABD for AndroidTool to work...

**Comment by clarklab** [comment]
ps if I can track down a Huawei dev phone for you, would you be interested in adding more support?

**Comment by clarklab** [comment]
think I figured it out— my Huawei phone is running 4.3, and screenrecord is only for 4.4+ devices, haha 

sorry to waste your time!

**Comment by mortenjust** [comment]
Oh, awesome! Not wasting my time at all, now I have another question to ask next time. Thanks!

**Comment by clarklab** [comment]
Unrelated: do you need/want any design help on this project? I'd love to
pitch in on the app or website or whatever. This little thing is killer,
and I see myself using it a lot in the future....

**Comment by mortenjust** [comment]
Would be great. I think the website could be a lot better. Any ideas? Are you able to code the template too?

**Comment by mortenjust** [comment]
This is the website, btw http://mortenjust.github.io/androidtool-mac/

**Comment by clarklab** [comment]
Yessir, full frontend chops to match. I can do frontend + WP (fulltime for
like 8 years now) or Jekyll (new bag but learning quick).

Some work at http://clarklab.com

Currently doing content at InVision, previously UX/frontend at The Zebra.
