### ISSUE TITLE
Request: Screenshot Rename

### ISSUE THREAD

**Issue by WinDroidGuy** [mortenjust/androidtool-mac#46]
Would be nice to be able to rename or set a specific name before we take them. This would be useful if taking app screenshots, then you can set a folder/set with a specific name.

**Comment by mortenjust** [comment]
We've got custom folders running in a local branch right now. I'll release it once it's tested a bit more (and back from traveling)

**Comment by ChristianBecker** [comment]
Any progress on this? I would highly appreciate the possibility to set a custom folder for the screenshots…

**Comment by mortenjust** [comment]
Lost that original code, but it's moving through the pipes right now

![image](https://cloud.githubusercontent.com/assets/1548468/11517406/236bc21e-983e-11e5-8e33-794d1c986843.png)

**Comment by mortenjust** [comment]
Added in 1.5, check it out! @WinDroidGuy, your use case might be solved by the new "Use activity in filename" feature. But more direct file naming is definitely also an option. 

https://github.com/mortenjust/androidtool-mac/releases
