### ISSUE TITLE
video can`t be recorded 

### ISSUE THREAD

**Issue by athulcek** [mortenjust/androidtool-mac#49]
video recording is not working the button is not responding

**Comment by clarklab** [comment]
What version of Android is your device running?

Related: sometimes the button looks like it's not responding, but the videos are being recorded anyway.

**Comment by athulcek** [comment]
android 4.0.3

**Comment by athulcek** [comment]
![dblackiml74kathulbabu05212015123137](https://cloud.githubusercontent.com/assets/4416169/7743160/a7741e98-ffb5-11e4-8990-460dfe3ec2d2.png)

**Comment by clarklab** [comment]
This tool uses the adb command `screenrecord` which is only available in devices with Android 4.4+

(we just learned this, probably add it to the docs soon)

**Comment by athulcek** [comment]
ok thank you

**Comment by mortenjust** [comment]
Thanks guys, I started an FAQ here https://github.com/mortenjust/androidtool-mac/wiki/FAQ
