### ISSUE TITLE
Request: Set battery level / hide status icons for Android

### ISSUE THREAD

**Issue by clarklab** [mortenjust/androidtool-mac#50]
When recording on iOS, the battery is shown full and the time is set to 9:41. Is there a way to enable something on Android devices? Bonus points: hide the status icons (since USB debugging and a few others are usually present in the captures).

Possible? Does ADB allow this?

**Comment by kyhule** [comment]
@clarklab If you are recording from a device that has the play store installed, check out: https://play.google.com/store/apps/details?id=com.emmaguy.cleanstatusbar

**Comment by davekover** [comment]
@clarklab If you are on a device with 6.0, you could enable demo mode which will have the effect you are looking for.

**Comment by mortenjust** [comment]
Nice, @davekover. Seems this can be done over ADB, so AndroidTool could too. https://android.googlesource.com/platform/frameworks/base/+/android-6.0.0_r1/packages/SystemUI/docs/demo_mode.md

**Comment by mortenjust** [comment]
I'm thinking
* No notification icons
* Time set to 10:09am (like iOS for consistency)
* Battery 100% and not plugged in
* Full cell signal, but no datatype (like LTE, 3G, etc)

**Comment by mortenjust** [comment]
This is now implemented in the latest version! 

![image](https://cloud.githubusercontent.com/assets/1548468/11384591/d54efc40-92c5-11e5-8303-dae1d648017e.png)
