### ISSUE TITLE
Request:  Start recording countdown and recording light

### ISSUE THREAD

**Issue by TheIcemanCometh** [mortenjust/androidtool-mac#54]
For video recording, I would like a configurable option to be able to have a countdown timer before recording starts, say 0 to 10 seconds, with a countdown beep the last three seconds.

Also, I would like to see a red light on the app screen that lets me know video is currently recording.  This should flash every couple of seconds while recording is active.

**Comment by mortenjust** [comment]
As of 1.4, the recording button now becomes a red stop button
