### ISSUE TITLE
Screenshot doesn't work with stock emulator, but adb shell command works fine

### ISSUE THREAD

**Issue by afollestad** [mortenjust/androidtool-mac#57]
`adb shell screencap -p /path` works fine, but Android Tool disables the screenshot button.

**Comment by binaryfork** [comment]
On Genymotion emulator the screenshot button is also disabled until you press the video button, then screenshots are working fine.

**Comment by mortenjust** [comment]
Please try downloading the latest version, then Tools > Output window. Try taking a screenshot, and then paste the output here. Please reopen the issue when you reply. Thanks!
