### ISSUE TITLE
bug report fails if AndroidTool folder has not yet been created.

### ISSUE THREAD

**Issue by soundanalogous** [mortenjust/androidtool-mac#58]
If you try to take a bug report before taking a screen shot (or otherwise creating the AndroidTool folder) then the bug report will fail.

**Comment by soundanalogous** [comment]
Also, I noticed a "bugreport" folder is created when you click the "Take Bugreport" option. Maybe the issue is that "bugreport" folder should be targeted instead of the "AndroidTool" folder?

**Comment by mortenjust** [comment]
Just took a report with no AndroidTool folder, so it seems to be fixed in 1.42. For people with this bug, updating alone might not be enough, as "Take bugreport.sh" is saved in Application Support. Delete that folder, or grab the shell script from the repo and you're all set for bug report take off
