### ISSUE TITLE
Capturing from Android Wear

### ISSUE THREAD

**Issue by clarklab** [mortenjust/androidtool-mac#59]
I see in the examples that capturing from a watch should work but I can't seem to figure it out. I've got dev mode turned on the watch, but the only options I see are for Bluetooth ADB. What should I be doing next?

**Comment by jlhonora** [comment]
Check issue #5

**Comment by mortenjust** [comment]
@clarklab if your watch has a direct usb from the cradle that's by far the easiest way to go.
