### ISSUE TITLE
video recording is not working in nexus 7 2013

### ISSUE THREAD

**Issue by techgeeksid** [mortenjust/androidtool-mac#63]
<img width="662" alt="screen shot 2015-08-21 at 7 06 42 pm" src="https://cloud.githubusercontent.com/assets/8020189/9409395/db1f9bc6-4837-11e5-9050-0c841ac8ff6a.png">

**Comment by iamyae** [comment]
Maybe you could try to use a lower resolution to record.On my Samsung Tab S (2560x1600), it meets the same problem if I use the original resolution.When set to 1280x800, it'll be just OK.Hope this could help u.

Date: Fri, 21 Aug 2015 06:37:55 -0700

**Comment by mortenjust** [comment]
Hey @techgeeksid, did @iamyae's suggestion work for you?
