### ISSUE TITLE
Video Recording is  not support Meizu M2 Note

### ISSUE THREAD

**Issue by lusfold** [mortenjust/androidtool-mac#64]
### Video Recording is  not support Meizu M2 Note

when click record button,nothing happened

**Comment by mortenjust** [comment]
Does screen recording with adb work on your Meizu M2 Note?

http://www.androidauthority.com/android-customization-screen-recording-adb-599331/

**Comment by lusfold** [comment]
adb shell screenrecord is ok and Android Studio screen recording is ok too.

**Comment by mortenjust** [comment]
Can you attach a screenshot of AndroidTool while it's plugged in to you phone?

**Comment by mortenjust** [comment]
Please try downloading the latest version. Then Tools > Terminal output. Try again. Copy the output and paste here
