### ISSUE TITLE
Video recording issues (choppy output)

### ISSUE THREAD

**Issue by gwongsta** [mortenjust/androidtool-mac#65]
Is there any way to fix a video screen recording that's choppy? I am recording my screen on a Note 3 and no matter what bitrate or resolution I use, although the quality is perfect, there is choppiness when recording gameplay such as Clash of Clans. Any suggestions for fixes that I could possibly do on my device's end?

**Comment by mortenjust** [comment]
Unfortunately it sounds like your device doesn't have CPU cycles to do both recording and a potentially performance heavy game
