### ISSUE TITLE
video recording is not working in HTC 300

### ISSUE THREAD

**Issue by geopayme** [mortenjust/androidtool-mac#66]
When you click the record button, nothing happens...

**Comment by mortenjust** [comment]
It seems there is a bug where the record button doesn't change state whilie
it is recording. What happens if you close AndroidTool > Open AndroidTool >
Wait for the button to be active > Press the button > Wait 20 seconds >
Press the button again?

**Comment by geopayme** [comment]
Tried it nothing happen...

**Comment by geopayme** [comment]
I dont see the record button active, its grey is that the active state?

On Mon, Sep 28, 2015 at 8:52 PM, Morten Just <notifications@github.com>
wrote:

> It seems there is a bug where the record button doesn't change state whilie
> it is recording. What happens if you close AndroidTool > Open AndroidTool >
> Wait for the button to be active > Press the button > Wait 20 seconds >
> Press the button again?
>
> On Mon, Sep 28, 2015 at 2:33 AM Adonis Valamontes <
> notifications@github.com>
> wrote:
>
> > When you click the record button, nothing happens...
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/mortenjust/androidtool-mac/issues/66>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mortenjust/androidtool-mac/issues/66#issuecomment-143822225>
> .
>



-- 
Geopay.me Inc.

*"don't need to know everything, I just need to know where to find it."**A.
Einstein.*
If you need to reach your people really fast, there's no better way to do
it than with "mobile".

Mobile is direct, accurate, and personal.

This email may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this email by mistake),
please notify the sender immediately and destroy this email. Any
unauthorised copying, disclosure or distribution of the material in this
email is strictly prohibited.

Email transmission security and error-free status cannot be guaranteed as
information could be intercepted, corrupted, destroyed, delayed,
incomplete, or contain viruses. The sender therefore does not accept
liability for any errors or omissions in the contents of this message
which may arise as a result of email transmission.

**Comment by mortenjust** [comment]
Just confirming that you do in fact run at least 4.4 KitKat, right? 

It should have the same color as the camera in the screenshot button next to it. Sounds like the HTC is not reacting to the tool's request for display size info. That's fixable, but probably only by someone who has the same model and Android version.

**Comment by geopayme** [comment]
I have HTC Desire 300

Android 4.1.2

On Mon, Sep 28, 2015 at 10:06 PM, Morten Just <notifications@github.com>
wrote:

> Just confirming that you do in fact run at least 4.4 KitKat, right?
>
> It should have the same color as the camera in the screenshot button next
> to it. Sounds like the HTC is not reacting to the tool's request for
> display size info. That's fixable, but probably only by someone who has the
> same model and Android version.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mortenjust/androidtool-mac/issues/66#issuecomment-143845922>
> .
>



-- 
Geopay.me Inc.

*"don't need to know everything, I just need to know where to find it."**A.
Einstein.*
If you need to reach your people really fast, there's no better way to do
it than with "mobile".

Mobile is direct, accurate, and personal.

This email may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this email by mistake),
please notify the sender immediately and destroy this email. Any
unauthorised copying, disclosure or distribution of the material in this
email is strictly prohibited.

Email transmission security and error-free status cannot be guaranteed as
information could be intercepted, corrupted, destroyed, delayed,
incomplete, or contain viruses. The sender therefore does not accept
liability for any errors or omissions in the contents of this message
which may arise as a result of email transmission.

**Comment by geopayme** [comment]
I cant take screen shots but no video

On Mon, Sep 28, 2015 at 10:06 PM, Morten Just <notifications@github.com>
wrote:

> Just confirming that you do in fact run at least 4.4 KitKat, right?
>
> It should have the same color as the camera in the screenshot button next
> to it. Sounds like the HTC is not reacting to the tool's request for
> display size info. That's fixable, but probably only by someone who has the
> same model and Android version.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mortenjust/androidtool-mac/issues/66#issuecomment-143845922>
> .
>



-- 
Geopay.me Inc.

*"don't need to know everything, I just need to know where to find it."**A.
Einstein.*
If you need to reach your people really fast, there's no better way to do
it than with "mobile".

Mobile is direct, accurate, and personal.

This email may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this email by mistake),
please notify the sender immediately and destroy this email. Any
unauthorised copying, disclosure or distribution of the material in this
email is strictly prohibited.

Email transmission security and error-free status cannot be guaranteed as
information could be intercepted, corrupted, destroyed, delayed,
incomplete, or contain viruses. The sender therefore does not accept
liability for any errors or omissions in the contents of this message
which may arise as a result of email transmission.

**Comment by geopayme** [comment]
correction

I CAN TAKE SCREEN SHOTS

On Mon, Sep 28, 2015 at 10:06 PM, Morten Just <notifications@github.com>
wrote:

> Just confirming that you do in fact run at least 4.4 KitKat, right?
>
> It should have the same color as the camera in the screenshot button next
> to it. Sounds like the HTC is not reacting to the tool's request for
> display size info. That's fixable, but probably only by someone who has the
> same model and Android version.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mortenjust/androidtool-mac/issues/66#issuecomment-143845922>
> .
>



-- 
Geopay.me Inc.

*"don't need to know everything, I just need to know where to find it."**A.
Einstein.*
If you need to reach your people really fast, there's no better way to do
it than with "mobile".

Mobile is direct, accurate, and personal.

This email may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this email by mistake),
please notify the sender immediately and destroy this email. Any
unauthorised copying, disclosure or distribution of the material in this
email is strictly prohibited.

Email transmission security and error-free status cannot be guaranteed as
information could be intercepted, corrupted, destroyed, delayed,
incomplete, or contain viruses. The sender therefore does not accept
liability for any errors or omissions in the contents of this message
which may arise as a result of email transmission.

**Comment by mortenjust** [comment]
Ah, screen recording isn't supported before 4.4. 

I'm happy that you can take screen shots though.
