### ISSUE TITLE
Video Recording not working on Micromax A106

### ISSUE THREAD

**Issue by piyushmakhija** [mortenjust/androidtool-mac#72]
![androidtool_error](https://cloud.githubusercontent.com/assets/5974717/11365787/0281601e-92cf-11e5-84ea-301d5634dafd.gif)

Android version : 4.4.2
![a106kot49hpiyush11242015171658](https://cloud.githubusercontent.com/assets/5974717/11365929/fe4614b2-92cf-11e5-8af8-88dc5066389b.png)
Screenshots working fine on androidtool.
Video recording is working with 'adb shell screenrecord' but not with androidtool.

**Comment by mortenjust** [comment]
Hi, please do this 

* Download the latest version
* Go to Tools > Terminal Output
* Try recording again 
* Paste the output here

**Comment by piyushmakhija** [comment]
Works fine on Androidtool 1.42. Thanks!
