### ISSUE TITLE
A choosable gif-generating function maybe?

### ISSUE THREAD

**Issue by hanbang-wang** [mortenjust/androidtool-mac#75]
It always auto generates gif even I recorded a long video, which takes up all my computer resources and I don't even need it.

**Comment by mortenjust** [comment]
Good point. Added to the <a href="https://github.com/mortenjust/androidtool-mac/releases">most recent version</a> and disabled by default. Thanks for the feedback!

<img width="556" alt="screenshot-32" src="https://cloud.githubusercontent.com/assets/1548468/11650968/1f50bf14-9d42-11e5-96ba-97bcd5d9f993.png">
