### ISSUE TITLE
Display phone screen on desktop directly?

### ISSUE THREAD

**Issue by acely** [mortenjust/androidtool-mac#77]
Hi
Thanks for your excellent work!
Wondering if it's possible to display my phone content directly on to one window?

Now the tool can get the video stream to ffmpeg and write to file,
so I think it possible to show the video stream into a simple player can also be done.

**Comment by mortenjust** [comment]
Currently the screen is not streamed to ffmpeg directly. Rather, it is recorded onto the device's storage, then transferred, and then converted. But there might be ways to do what you describe. Was there a specific use case you had in mind?

**Comment by acely** [comment]
Thanks for the reply!
The case is,I'm a product manager,and lead a team to develop an Android APP.
When one version is in testing progress, I want to show my team mates where the ux is different than I've designed,or show them how other app handles the ux as example.

As my computer is connected to the projector when meeting,so it would be very handful if I can show phone content directly on my screen~

Thanks again!

**Comment by dsspence** [comment]
@acely We've had success with vysor.io

**Comment by acely** [comment]
@dsspence OMG！That is surprisingly wonderful！
Thanks sooooooooooooooo much!
I feel that you're opening a door to a whole new level!

**Comment by mortenjust** [comment]
Awesome
