### ISSUE TITLE
Video recording stops after 3 mimnutes

### ISSUE THREAD

**Issue by RaoGobburu** [mortenjust/androidtool-mac#78]
Thanks a lot for a great solution!
Not sure if this is an issue or just a feature. Is there any way to get longer video recordings? My recordings stop after 3 minutes.
I have tested with version 1.56 as well as earlier versions and see the same behavior.
It is not dependent on the Android phone connected.

**Comment by mortenjust** [comment]
The limit seems to be up to the handset manufacturer, and maybe also determined by the amount of available space on the phone's memory. For long videos and presentations, you could look into http://www.airsquirrels.com/reflector/ for now.

**Comment by mortenjust** [comment]
If you want you can try the manual process and see if there is a difference: 

https://github.com/mortenjust/androidtool-mac/wiki/Troubleshooting

**Comment by mortenjust** [comment]
Looking further into this it turns out that recordings are limited to 3 minutes by the Android framework https://android.googlesource.com/platform/frameworks/av/+/lollipop-release/cmds/screenrecord/screenrecord.cpp

**Comment by RaoGobburu** [comment]
Hi Morten
Thanks a lot for your help....
Too bad the limit is 3 minutes... not a big issue but a inconvenience.

Once again - the AndroidTool is just a super useful tool. Thanks a lot.

Best regards
Rao
