### ISSUE TITLE
No devices appear on Mavericks (10.9.x)

### ISSUE THREAD

**Issue by mars3142** [mortenjust/androidtool-mac#8]
The AndroidTool window is empty, where I should see any connected devices. **adb devices** show my device attached. Is there any debug log, what I can check?

**Comment by mars3142** [comment]
I use OS X 10.9.5 - may be this help you.

**Comment by mortenjust** [comment]
Is it stil the case if you switch to another app and then back to AndroidTool? Which Android devices have you tried with?

**Comment by mars3142** [comment]
My Android device is a Nexus 4 (Android 5.1).

![androidtool](https://cloud.githubusercontent.com/assets/220423/7379502/ab7922d0-edf5-11e4-9739-6cdcb06cdf21.png)

**Comment by mortenjust** [comment]
Thanks. I'll check with Mavericks and Nexus 4

**Comment by dextorer** [comment]
Same on Mavericks, regardless of the device (N5, G3, ..).

**Comment by HannahMitt** [comment]
See same issue on Mavericks with N5.

**Comment by NicolasPietri** [comment]
Seeing same issue on Mavericks with Moto X 2nd gen.

**Comment by quanturium** [comment]
Same issue here, Mavericks, with many different devices and emulators

**Comment by mortenjust** [comment]
Should work in the latest version on https://github.com/mortenjust/androidtool-mac/releases

Please make sure you select "Always allow from this computer" in the "Allow USB debugging" dialog that pops up on the phone when plugging it into the computer for the first time
