### ISSUE TITLE
video recording button not working, grayed out, not clickable

### ISSUE THREAD

**Issue by kristofgiber** [mortenjust/androidtool-mac#80]
I have El Captain and my android device is SM-G350 (4.2.2).
I've just downloaded it for the first time but video recording doesn't happen. 
Tried both 1.51 and 1.56 directly downloaded the zip and just launched the unpacked tool. Even tried reinstalling from terminal with Homebrew, it's all the same. My device is detected when I connect it, Screen shot works fine when I click on it, but video recording doesn't. The video recording button shown in the tutorials is there but nothing happens when I click.

**Comment by mortenjust** [comment]
Thanks for the report. Please try this

1. Unplug all phones
2. Open the latest version of the app
3. Go to Tools > Terminal output and check "Verbose"
4. Plug in your phone
5. Wait one minute
6. Paste the contents of the terminal output window here

**Comment by kristofgiber** [comment]
Thank you for getting back! 
Here we go. I've removed some personal data but there's a lot in there so I'll edit and remove the whole output from this post once you've got it. Let me know if I've removed too much.

/Applications/AndroidTool 2.app/Contents/Resources/getDetailsForSerial.sh
[awesome.lateness]: [200]
[boot.sfbootcomplete]: [1]
[dalvik.vm.dexopt-flags]: [m=y]
[dalvik.vm.heapgrowthlimit]: [48m]
[dalvik.vm.heapsize]: [128m]
[dalvik.vm.heapstartsize]: [5m]
[dalvik.vm.stack-trace-file]: [/data/anr/traces.txt]
[debug.brcm.fbdump]: [0]
[debug.hwui.render_dirty_regions]: [false]
[dev.MDPLimitCondition]: [0]
[dev.bootcomplete]: [1]
[dev.extended_dump_layer_on]: [0]
[dev.kies.sommode]: [FALSE]
[dhcp.wlan0.dns2]: []
[dhcp.wlan0.dns3]: []
[dhcp.wlan0.dns4]: []
[dhcp.wlan0.leasetime]: [43200]
[dhcp.wlan0.mask]: [255.255.255.0]
[dhcp.wlan0.reason]: [REBOOT]
[dhcp.wlan0.result]: [ok]
[dhcp.wlan0.roaming]: [0]
[dhcp.wlan0.vendorInfo]: []
[drm.service.enabled]: [true]
[fb.force.dithering]: [1]
[gralloc.use_sync_mode]: [true]
[gsm.current.phone-type]: [1]
[gsm.network.type]: [HSDPA:9]
[gsm.operator.alpha]: []
[gsm.operator.iso-country]: [fr]
[gsm.operator.isroaming]: [false]
[gsm.sim.state]: [READY]
[gsm.version.baseband]: [G350XXU0ANG4]
[gsm.version.ril-impl]: [BRCM android bcm-ril-090728]
[init.svc.adbd]: [running]
[init.svc.at_distributor]: [running]
[init.svc.bkmgrd]: [running]
[init.svc.bootanim]: [stopped]
[init.svc.bugreport]: [stopped]
[init.svc.console]: [running]
[init.svc.debuggerd]: [running]
[init.svc.dhcpcd_wlan0]: [running]
[init.svc.drm]: [running]
[init.svc.flash_recovery]: [stopped]
[init.svc.gpsd]: [running]
[init.svc.installd]: [running]
[init.svc.iprenew_wlan0]: [stopped]
[init.svc.keystore]: [running]
[init.svc.macloader]: [stopped]
[init.svc.media]: [running]
[init.svc.mobex-daemon]: [running]
[init.svc.netd]: [running]
[init.svc.p2p_supplicant]: [running]
[init.svc.powersnd]: [stopped]
[init.svc.ril-daemon]: [running]
[init.svc.rtccd]: [stopped]
[init.svc.sdcard]: [stopped]
[init.svc.sensord]: [running]
[init.svc.servicemanager]: [running]
[init.svc.setup_fs]: [stopped]
[init.svc.surfaceflinger]: [running]
[init.svc.ueventd]: [running]
[init.svc.usb_portd]: [running]
[init.svc.vold]: [running]
[init.svc.wpa_supplicant]: [running]
[init.svc.zygote]: [running]
[installd.sdcard_manipulate_done]: [1]
[keyguard.no_require_sim]: [true]
[media.enable-commonsource]: [true]
[net.bt.name]: [Android]
[net.change]: [net.wlan0.dns2]
[net.dnschange]: [3]
[net.qtaguid_enabled]: [1]
[net.streaming.rtsp.uaprof]: [http://wap.samsungmobile.com/uaprof/]
[net.tcp.buffersize.default]: [4096,87380,704512,4096,16384,110208]
[net.tcp.buffersize.edge]: [4093,26280,35040,4096,16384,35040]
[net.tcp.buffersize.evdo]: [4094,87380,262144,4096,16384,262144]
[net.tcp.buffersize.gprs]: [4096,30000,30000,4096,8760,11680]
[net.tcp.buffersize.hsdpa]: [4094,174760,563200,4096,16384,262144]
[net.tcp.buffersize.hspa]: [4094,174760,563200,4096,16384,262144]
[net.tcp.buffersize.hspap]: [4094,174760,563200,4096,16384,262144]
[net.tcp.buffersize.hsupa]: [4094,174760,563200,4096,16384,262144]
[net.tcp.buffersize.lte]: [524288,1048576,2560000,524288,1048576,2560000]
[net.tcp.buffersize.umts]: [4094,87380,704512,4096,16384,110208]
[net.tcp.buffersize.wifi]: [524288,1048576,2097152,262144,524288,1048576]
[net.wlan0.dns1]: [49.0.0.0]
[net.wlan0.dns2]: []
[nuplayer.eos.timeout]: [3]
[persist.audio.allsoundmute]: [0]
[persist.audio.headsetsysvolume]: [4]
[persist.audio.hphonesysvolume]: [4]
[persist.audio.ringermode]: [1]
[persist.audio.sysvolume]: [4]
[persist.brcm.ap_crash]: [none]
[persist.brcm.cp_crash]: [none]
[persist.brcm.log]: [none]
[persist.radio.gprsattachmode]: [1]
[persist.radio.icc.cb.count]: [0]
[persist.radio.icc.cb.list]: []
[persist.radio.initphone-type]: [1]
[persist.radio.networkband]: [1]
[persist.radio.networktype]: [0]
[persist.radio.networktype_1]: [1]
[persist.radio.plmnname_2]: []
[persist.radio.rpcloglevel]: [1]
[persist.radio.wbamr]: [0]
[persist.sys.bpmsetting.enable]: [0]
[persist.sys.cmas.enable]: [0]
[persist.sys.language]: [en]
[persist.sys.localevar]: []
[persist.sys.profiler_ms]: [0]
[persist.sys.screen.rotation.Off]: [-1]
[persist.sys.setupwizard]: [FINISH]
[persist.sys.storage_preload]: [2]
[persist.sys.timezone]: [Europe/Paris]
[persist.sys.usb.config]: [mtp,adb]
[persist.sys.usb.mobex]: [0]
[ril.GID1]: [FF]
[ril.GID2]: [FF]
[ril.ICC_TYPE]: [2]
[ril.MNC_LEN]: [02]
[ril.MSIMM]: [0]
[ril.RildInit]: [1]
[ril.approved_codever]: [none]
[ril.approved_cscver]: [none]
[ril.approved_modemver]: [none]
[ril.atd_status]: [1_1_0]
[ril.boot_completed]: [1]
[ril.deviceOffRes]: [1]
[ril.ecclist0]: [112,911,112,911]
[ril.gdataprefer]: [0]
[ril.hw_ver]: [MP 0.701]
[ril.initPB]: [1]
[ril.init]: [1]
[ril.isIccChanged]: [0]
[ril.official_cscver]: [G350OXA0ANG5]
[ril.pba]: [F]
[ril.rfcal_date]: [20140721]
[ril.sensor.cal]: [XXXXXXX000000000000000000100000]
[ril.servicestate]: [2]
[ril.smd]: [P]
[ril.sw_ver]: [G350XXU0ANG4]
[ril.tethering.usb.active]: [0]
[rild.libpath]: [/system/lib/libbrcm_ril.so]
[ro.adb.qemud]: [1]
[ro.adb.secure]: [1]
[ro.allow.mock.location]: [0]
[ro.baseband]: [unknown]
[ro.board.platform]: [hawaii]
[ro.boot.console]: [ttyS2]
[ro.boot.debug_level]: [0x4f4c]
[ro.boot.emmc_checksum]: [3]
[ro.bootloader]: [unknown]
[ro.bootmode]: [unknown]
[ro.bt.bdaddr_path]: [/efs/bluetooth/bt_addr]
[ro.build.PDA]: [G350XXU0ANG4]
[ro.build.changelist]: [2722265]
[ro.build.characteristics]: [phone]
[ro.build.date.utc]: [1406274271]
[ro.build.date]: [Fri Jul 25 16:44:31 KST 2014]
[ro.build.description]: [cs02xx-user 4.2.2 JDQ39 G350XXU0ANG4 release-keys]
[ro.build.display.id]: [JDQ39.G350XXU0ANG4]
[ro.build.fingerprint]: [samsung/cs02xx/cs02:4.2.2/JDQ39/G350XXU0ANG4:user/release-keys]
[ro.build.hidden_ver]: [G350XXU0ANG4]
[ro.build.host]: [SEP-132]
[ro.build.id]: [JDQ39]
[ro.build.product]: [cs02]
[ro.build.tags]: [release-keys]
[ro.build.type]: [user]
[ro.build.user]: [se.infra]
[ro.build.version.codename]: [REL]
[ro.build.version.incremental]: [G350XXU0ANG4]
[ro.build.version.release]: [4.2.2]
[ro.build.version.sdk]: [17]
[ro.carrier]: [unknown]
[ro.chipname]: [hawaii]
[ro.com.android.dateformat]: [MM-dd-yyyy]
[ro.com.google.clientidbase]: [android-samsung]
[ro.com.google.gmsversion]: [4.2_r6]
[ro.crypto.fuse_sdcard]: [true]
[ro.crypto.support]: [recovery_mount|others]
[ro.csc.sales_code]: [XEF]
[ro.debug_level]: [0x4f4c]
[ro.debuggable]: [0]
[ro.emmc_checksum]: [3]
[ro.error.receiver.default]: [com.samsung.receiver.error]
[ro.factorytest]: [0]
[ro.hardware]: [hawaii_ss_cs02]
[ro.kernel.qemu]: [0]
[ro.lcd_brightness]: [160]
[ro.nfc.port]: [I2C]
[ro.opengles.version]: [131072]
[ro.product.board]: [hawaii]
[ro.product.brand]: [samsung]
[ro.product.cpu.abi2]: [armeabi]
[ro.product.cpu.abi]: [armeabi-v7a]
[ro.product.device]: [cs02]
[ro.product.locale.language]: [en]
[ro.product.locale.region]: [GB]
[ro.product.manufacturer]: [samsung]
[ro.product.max_num_touch]: [2]
[ro.product.model]: [SM-G350]
[ro.product.multi_touch_enabled]: [true]
[ro.product.name]: [cs02xx]
[ro.product_ship]: [true]
[ro.revision]: [2]
[ro.ril.ecclist]: [112,911]
[ro.ril.gprsclass]: [10]
[ro.ril.hsxpa]: [1]
[ro.runtime.firstboot]: [1451234123851]
[ro.sec.fle.encryption]: [true]
[ro.secure]: [1]
[ro.serialno]: [4203f750d6b07100]
[ro.setupwizard.mode]: [DISABLED]
[ro.sf.lcd_density]: [240]
[ro.telephony.call_ring.multiple]: [0]
[ro.tvout.enable]: [false]
[ro.url.legal.android_privacy]: [http://www.google.com/intl/%s/mobile/android/basic/privacy.html]
[ro.url.legal]: [http://www.google.com/intl/%s/mobile/android/basic/phone-legal.html]
[ro.wap.push]: [0]
[ro.wifi.channels]: []
[secmm.player.aiastate]: [False]
[service.bootanim.exit]: [1]
[service.camera.running]: [0]
[service.media.powersnd]: [1]
[service.tether.active]: [0]
[sf.metadata_retrv_hw_codecs]: [1]
[sf.metadata_use_plat_sw_codecs]: [1]
[status.battery.level]: [10]
[status.battery.level_raw]: [100]
[status.battery.level_scale]: [10]
[status.battery.state]: [Slow]
[storage.mmc.size]: [3909091328]
[sys.boot_completed]: [1]
[sys.dumpstate.opt]: [-k -t -z -d -o /data/log/dumpstate_app_anr]
[sys.factory.mediaScanningCount]: [58]
[sys.hangouts.fps]: [-1]
[sys.im.enable.vibrator]: [false]
[sys.settings_global_version]: [9]
[sys.settings_secure_version]: [2]
[sys.settings_system_version]: [418]
[sys.usb.config]: [mtp,adb]
[sys.usb.state]: [mtp,adb]
[system_init.startsurfaceflinger]: [0]
[video.enc.h264.adaptive_quality]: [1]
[video.enc.h264.timing_thr0]: [295]
[video.enc.h264.timing_thr1]: [215]
[video.enc.h264.timing_thr2]: [145]
[video.enc.h264.timing_window_sz]: [4]
[vold.post_fs_data_done]: [1]
[wifi.interface]: [wlan0]
[wlan.driver.status]: [ok]
[wlan.wfd.status]: [disconnected]

/Applications/AndroidTool 2.app/Contents/Resources/getResolutionForSerial.sh
doing this:-------
/Applications/AndroidTool 2.app/Contents/Resources/adb -s 4203f750d6b07100 shell wm size
-----------
/system/bin/sh: wm: not found

**Comment by mortenjust** [comment]
Ah okay, which phone model and Android version do you have?

**Comment by kristofgiber** [comment]
I have Samsung Galaxy Core Plus (SM-G350), version 4.2.2.

Morten Just <notifications@github.com> ezt írta (2016. január 7.,
csütörtök):

**Comment by mortenjust** [comment]
Ah, ok. Video recording requires Android 4.4 KitKat.
