### ISSUE TITLE
Does screen recording come with sound?

### ISSUE THREAD

**Issue by ffmaer** [mortenjust/androidtool-mac#91]
I tried to record. The video looks fine. But it did not have sound.

**Comment by mriddle** [comment]
I was able to successfully record with

 * OS X 10.11.5
 * iPhone 6+ with iOS 9.3.2
 * AndroidTool version 1.62 downloaded from GitHub release page

Recorded a brief snippet of the youtube app playing a random video.

Was this recording android or iOS? What version of the app were you running? What are the details of the device?

**Comment by tonytranupc** [comment]
There is another tool that you can use to take screenshot on Mac or record Mac screen. It's called SnagIt. Read more from here:

[https://usefulpcguide.com/17662/best-screen-capture-tools-mac/](https://usefulpcguide.com/17662/best-screen-capture-tools-mac/)

**Comment by mortenjust** [comment]
Thanks, @tonytranupc !
