### ISSUE TITLE
Crashes once device is connected

### ISSUE THREAD

**Issue by ahnclara** [mortenjust/androidtool-mac#96]
AndroidTool ver 1.6, 1.61, 1.62 all crash when a device is connected.
I tried uninstalling and re-installing, hardware re-imaging, etc. but it is still not working.

**Comment by mriddle** [comment]
Hey @ahnclara I'll try to help out if I can but first I'll need a few more details to get a better understanding of the issue.

* Were you trying to connect an Android device or an iOS device? What version of OS was the device running? 
* What operating system are you using and what version is it?
* What's your terminal output?  `AndroidTool > Tools > Terminal Output` or ⇧⌘O

With that detail hopefully we'll be able to figure out what's going on.

**Comment by ahnclara** [comment]
Hi! so I switched out the computer and now it works fine.
I guess it was that particular latoptop.
Thank you so much for stepping in to help :)
